src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import (
    UserRegistrationView,
    UserLoginView,
    ActivateUserView,
    CustomUserProfileUpdateView,
    UserLogOutView,
    CustomUserProfileView,
    PrivacyPolicyView,
    CustomUserUpdateView,
    IndexView,
)
from accounts.views import NotFoundView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", IndexView.as_view(), name="index"),
    path("registration/", UserRegistrationView.as_view(), name="user_registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUserView.as_view(), name="activate"),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogOutView.as_view(), name="logout"),
    path("profile/<str:username>/", CustomUserProfileView.as_view(), name="profile"),
    path("user_settings/<uuid:pk>/", CustomUserUpdateView.as_view(), name="edit_customuser"),
    path("edit_profile/<uuid:pk>/", CustomUserProfileUpdateView.as_view(), name="edit_profile"),
    path("privacy_policy/", PrivacyPolicyView.as_view(), name="privacy"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = NotFoundView.as_view()

src/groups/urls.py
from django.urls import path
from groups.views import GroupListView, CreateGroupView, UpdateGroupView, DeleteGroupView

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>", DeleteGroupView.as_view(), name="delete_group"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import CreateTeacherView, UpdateTeacherView, DeleteTeacherView, ShowGroupsView, TeachersListView

app_name = "teachers"


urlpatterns = [
    path("", TeachersListView.as_view(), name="get_teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<str:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<str:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
    path("groups/<str:pk>/", ShowGroupsView.as_view(), name="show_groups"),
]

src/teachers/models.py
# import datetime
# import random
# import uuid
#
# from django.db import models
# from faker import Faker
#
#
# class Teacher(models.Model):
#     id = models.UUIDField(
#         primary_key=True,
#         unique=True,
#         editable=False,
#         default=uuid.uuid4,
#     )
#     first_name = models.CharField(max_length=128, null=True)
#     last_name = models.CharField(max_length=128, null=True)
#     email = models.EmailField(max_length=128)
#     birthday = models.DateField(null=True)
#     experience = models.SmallIntegerField(null=True)
#     salary = models.SmallIntegerField(null=True)
#     group = models.ManyToManyField(to="groups.Group", related_name="teachers")
#
#     def __str__(self):
#         return f"{self.first_name} {self.last_name} {self.email} {self.id}"
#
#     def age(self):
#         return datetime.datetime.now().year - self.birthday.year
#
#     def generate_teacher(self, count):
#         faker = Faker()
#
#         for _ in range(count):
#             salary = 2500 + random.randint(200, 500)
#             experience = random.randint(5, 15)
#             if 10 < experience < 30:
#                 salary += random.randrange(4000, 5000, 500)
#             elif 5 < experience <= 10:
#                 salary += random.randrange(3000, 4000, 200)
#             Teacher.objects.create(
#                 first_name=faker.first_name(),
#                 last_name=faker.last_name(),
#                 email=faker.email(),
#                 birthday=faker.date_time_between(start_date="-80y", end_date="-35y"),
#                 experience=experience,
#                 salary=salary,
#             )

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ("first_name", "last_name", "email", "birthday", "experience")

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex domain is forbidden")

        return email

    @staticmethod
    def normalize_text(text):
        return text.strip().capitalize()

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean(self):
        cleaned_data = super().clean()
        # extend parent method,  not overwrite

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name can't be equal")

        return cleaned_data

src/teachers/views.py
from django.forms.utils import ErrorList
from django.urls import reverse_lazy

from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, DetailView, ListView

from students.models import CustomUser
from students.views import UserAccessMixin


class IndexView(TemplateView):
    template_name = "index.html"
    http_method_names = ["get"]


class TeachersListView(ListView):
    model = CustomUser
    context_object_name = "teachers"
    template_name = "teachers_list.html"
    queryset = CustomUser.objects.filter(is_teacher=True)


class CreateTeacherView(UserAccessMixin, CreateView):
    permission_required = "teachers.change_teacher"
    login_url = "student_login"
    redirect_field_name = "next"

    template_name = "teachers_create.html"
    model = CustomUser
    fields = "__all__"
    success_url = reverse_lazy("teachers:get_teachers")
    initial = {"first_name": "John", "last_name": "Doe"}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        first_name = form.cleaned_data["first_name"]
        last_name = form.cleaned_data["last_name"]
        if first_name == last_name:
            form._errors["first_name"] = ErrorList(["First and last names can't be equal"])
            form._errors["last_name"] = ErrorList(["First and last names can't be equal"])
            return super().form_invalid(form)
        return super().form_valid(form)


class UpdateTeacherView(UserAccessMixin, UpdateView):
    permission_required = "teachers.change_teacher"
    login_url = "student_login"
    redirect_field_name = "next"

    model = CustomUser
    template_name = "edit_teacher.html"
    fields = "__all__"
    success_url = reverse_lazy("teachers:get_teachers")
    http_method_names = ["get", "post"]


class DeleteTeacherView(UserAccessMixin, DeleteView):
    permission_required = "teachers.change_teacher"
    login_url = "student_login"
    redirect_field_name = "next"

    model = CustomUser
    success_url = reverse_lazy("teachers:get_teachers")
    template_name = "delete_confirm.html"


class ShowGroupsView(DetailView):
    model = CustomUser
    template_name = "show_groups.html"


class NotFoundView(TemplateView):
    template_name = "404.html"

src/teachers/templates/delete_confirm.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <h4>{{ object.first_name }} {{ object.last_name }}</h4>
                <h5>Age: {{ object.age }} year(s)</h5>
                <h5>Experience: {{ object.experience }} year(s)</h5>
                <button type="submit" value="Delete" class="btn btn-warning">
                    Are you sure you want to delete "{{ object.first_name }} {{ object.last_name }}"?
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/teachers/templates/edit_teacher.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div>
        <form enctype="multipart/form-data" method="POST" class="create-form">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <button type="submit" value="Create" class="btn btn-success">
                    Confirm changes
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/teachers/templates/show_groups.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
     <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Experience</th>
            </tr>
            </thead>
                <tbody style="color:black; font-size:30px;">
                    <td >{{ object.first_name }}</td>
                    <td>{{ object.last_name }}</td>
                    <td>{{ object.experience }} year(s)</td>
                </tbody>
     </table>
 <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Department</th>
            <th scope="col">Course</th>
            <th scope="col">Letter</th>
            <th scope="col">Classroom</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>

        {% for group in object.group.all %}
            <tr>
                <th scope="row">{{ group.id }}</th>
                <td>{{ group.department }}</td>
                <td>{{ group.course }}</td>
                <td>{{ group.letter }}</td>
                <td>{{ group.classroom}}</td>
                <th scope="col"><a type="button" class="btn btn-warning"
                href="{% url 'groups:update_group' group.id  %}"> Edit</a></th>
            <th scope="col"><a type="button" class="btn btn-danger"
                href="{% url 'groups:delete_group' group.id  %}">Delete</a></th>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

src/teachers/templates/teachers_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div>
        <form method="POST" class="create-form">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <button type="submit" value="Create" class="btn btn-success">
                    Create
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/teachers/templates/teachers_list.html
{% extends "index.html" %}
{#    {% if user.is_authenticated %}#}
{% block content %}
    {% if user.is_staff %}
    <a href="{% url 'teachers:create_teacher' %}"
       class="btn btn-sm btn-success border-white ">Create new teacher's profile</a><br><br>
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birthdate</th>
            <th scope="col">Age</th>
            <th scope="col">Experience</th>
            <th scope="col">Groups</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                <th scope="row">{{ teacher.id }}</th>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.birthday }}</td>
                {% if teacher.birthday %}
                    <td>{{ teacher.age }}</td>
                {% else %}
                    <td>Undefined age</td>
                {% endif %}
               <td>{{ teacher.experience }}</td>
                <th scope="col"><a type="button" class="btn btn-success"
                href="{% url 'teachers:show_groups' teacher.id  %}">Show groups</a></th>
                <th scope="col"><a type="button" class="btn btn-warning"
                href="{% url 'teachers:update_teacher' teacher.id  %}"> Edit</a></th>
                <th scope="col"><a type="button" class="btn btn-danger"
                href="{% url 'teachers:delete_teacher' teacher.id  %}">Delete</a></th>
            </tr>

        {% endfor %}
                {% else %}
         <p class="lead">Access denied!</p>
                <p class="lead">Pls, Login to view current page!</p>
                <p class="lead">
                <a href="{% url "login" %}"
                   class="btn btn-lg btn-warning fw-normal border-white bg-white">Login</a>
        {% endif %}
        </tbody>
    </table>

{% endblock %}